-- ====================================================================
-- MYSHOP E-COMMERCE: COMPLETE SUPABASE BACKEND SCHEMA & SEED DATA
-- Run this in your Supabase Project Dashboard -> SQL Editor -> Run
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    original_price NUMERIC(10, 2),
    rating NUMERIC(3, 2) DEFAULT 4.5,
    reviews INTEGER DEFAULT 0,
    category TEXT,
    subcategory TEXT,
    image TEXT NOT NULL,
    images TEXT[],
    badge TEXT,
    description TEXT,
    colors TEXT[],
    sizes TEXT[],
    in_stock BOOLEAN DEFAULT TRUE,
    seller TEXT DEFAULT 'MyShop Verified Store',
    delivery_days INTEGER DEFAULT 3,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Ensure all columns exist if the table already existed with fewer columns
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS original_price NUMERIC(10, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS rating NUMERIC(3, 2) DEFAULT 4.5;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS reviews INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS subcategory TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS images TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS badge TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS colors TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sizes TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS in_stock BOOLEAN DEFAULT TRUE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS seller TEXT DEFAULT 'MyShop Verified Store';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS delivery_days INTEGER DEFAULT 3;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now());

-- Enable RLS for products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on products" ON public.products;
CREATE POLICY "Allow public read access on products"
    ON public.products FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow insert update for service role on products" ON public.products;
CREATE POLICY "Allow insert update for service role on products"
    ON public.products FOR ALL
    USING (auth.role() = 'service_role' OR auth.role() = 'authenticated');


-- 3. PROFILES TABLE (Linked with Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    avatar_url TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    country TEXT DEFAULT 'US',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
CREATE POLICY "Users can read own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

-- Trigger to automatically create a profile row when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email,
      full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 4. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip TEXT NOT NULL,
    country TEXT NOT NULL DEFAULT 'US',
    subtotal NUMERIC(10, 2) NOT NULL,
    delivery_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total NUMERIC(10, 2) NOT NULL,
    payment_method TEXT NOT NULL,
    payment_status TEXT NOT NULL DEFAULT 'paid',
    status TEXT NOT NULL DEFAULT 'processing',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow placing orders" ON public.orders;
CREATE POLICY "Allow placing orders"
    ON public.orders FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Users can read own orders" ON public.orders;
CREATE POLICY "Users can read own orders"
    ON public.orders FOR SELECT
    USING (
        auth.uid() = user_id 
        OR auth.uid() IS NULL 
        OR auth.role() = 'service_role'
    );


-- 5. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    product_name TEXT NOT NULL,
    product_image TEXT,
    price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    selected_color TEXT,
    selected_size TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow inserting order items" ON public.order_items;
CREATE POLICY "Allow inserting order items"
    ON public.order_items FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow reading order items" ON public.order_items;
CREATE POLICY "Allow reading order items"
    ON public.order_items FOR SELECT
    USING (true);


-- ====================================================================
-- 6. SEED DATA (Comprehensive Catalogue for All Categories)
-- ====================================================================

INSERT INTO public.products (
    id, name, price, original_price, rating, reviews, category, subcategory,
    image, images, badge, description, colors, sizes, in_stock, seller, delivery_days
) VALUES
(
    1,
    'Wireless Noise-Cancelling Headphones',
    79.99,
    129.99,
    4.5,
    234,
    'Electronics',
    'Audio',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop&auto=format'],
    'Sale',
    'Premium wireless headphones with active noise cancellation, 30-hour battery life, and ultra-comfortable ear cushions. Perfect for studying, commuting, or enjoying music.',
    ARRAY['#1A1A2E', '#4F46E5', '#F97316'],
    ARRAY['One Size'],
    TRUE,
    'TechHub Store',
    3
),
(
    2,
    'Classic Slim-Fit Hoodie',
    34.99,
    49.99,
    4.3,
    189,
    'Fashion',
    'Men',
    'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=600&fit=crop&auto=format'],
    'Hot',
    'A cozy, breathable hoodie made from 80% organic cotton and 20% recycled polyester. Features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs.',
    ARRAY['#374151', '#1D4ED8', '#6D28D9'],
    ARRAY['S', 'M', 'L', 'XL', 'XXL'],
    TRUE,
    'Campus Threads',
    4
),
(
    3,
    'Minimalist Smart Watch',
    149.99,
    199.99,
    4.7,
    312,
    'Accessories',
    'Wearables',
    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&h=600&fit=crop&auto=format'],
    'Sale',
    'A sleek smartwatch with health monitoring, GPS, and 7-day battery life. Tracks steps, heart rate, sleep, and stress. Compatible with iOS and Android.',
    ARRAY['#1A1A2E', '#E5E7EB', '#4F46E5'],
    ARRAY['One Size'],
    TRUE,
    'GadgetZone',
    2
),
(
    4,
    'Atomic Habits – James Clear',
    14.99,
    21.99,
    4.9,
    891,
    'Books',
    'Self-Help',
    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=600&fit=crop&auto=format'],
    'Hot',
    'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies to form good habits and break bad ones.',
    ARRAY[]::TEXT[],
    ARRAY['Hardcover', 'Paperback', 'Kindle'],
    TRUE,
    'BookLover Central',
    2
),
(
    5,
    'Pro Yoga & Fitness Mat',
    29.99,
    39.99,
    4.6,
    156,
    'Sports',
    'Fitness',
    'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=600&h=600&fit=crop&auto=format'],
    'New',
    'Extra-thick 6mm non-slip exercise yoga mat with alignment lines. Eco-friendly TPE material is waterproof, odor-free, and easy to clean.',
    ARRAY['#4F46E5', '#10B981', '#F59E0B'],
    ARRAY['Standard (72" x 24")'],
    TRUE,
    'ActiveLife Store',
    3
),
(
    6,
    'Ceramic Pour-Over Coffee Dripper',
    22.99,
    29.99,
    4.8,
    428,
    'Home',
    'Kitchen',
    'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=600&fit=crop&auto=format'],
    'Sale',
    'Handcrafted ceramic pour-over coffee dripper designed for optimal water flow and coffee extraction. Fits standard filters.',
    ARRAY['#FFFFFF', '#1A1A2E', '#D97706'],
    ARRAY['1-2 Cups', '2-4 Cups'],
    TRUE,
    'HomeCraft Co.',
    3
),
(
    7,
    'Ergonomic Mechanical Keyboard',
    89.99,
    119.99,
    4.7,
    275,
    'Electronics',
    'Computers',
    'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop&auto=format'],
    'Hot',
    'Compact 75% hot-swappable mechanical keyboard with RGB backlighting, custom switches, and multi-device Bluetooth / 2.4GHz wireless.',
    ARRAY['#1F2937', '#F3F4F6', '#6366F1'],
    ARRAY['Linear Red', 'Tactile Brown'],
    TRUE,
    'KeyCraft Labs',
    2
),
(
    8,
    'Canvas Weekender Travel Duffle',
    49.99,
    69.99,
    4.4,
    98,
    'Accessories',
    'Bags',
    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop&auto=format',
    ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&auto=format'],
    'Sale',
    'Heavy-duty waterproof canvas travel duffle bag with genuine leather trim, separate shoe compartment, and padded shoulder strap.',
    ARRAY['#4B5563', '#1E3A8A', '#78350F'],
    ARRAY['35 Liters', '45 Liters'],
    TRUE,
    'Wanderlust Gear',
    3
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price,
    rating = EXCLUDED.rating,
    reviews = EXCLUDED.reviews,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    image = EXCLUDED.image,
    images = EXCLUDED.images,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    colors = EXCLUDED.colors,
    sizes = EXCLUDED.sizes,
    in_stock = EXCLUDED.in_stock,
    seller = EXCLUDED.seller,
    delivery_days = EXCLUDED.delivery_days;
